구글 로그인 구현
ttbkk-univ/ttbkk-web pull request #103
Opened 2022-07-10 13:25 UTC by Uwa-Tech

spring- google login 이랑
admin - google login 참조해서 작성했습니다.
참조 : https://www.npmjs.com/package/react-google-login

2022-07-10 17:04 UTC, siner308 commented on src/components/Features/Sidebar/SIdebarDetail/Logins/index.tsx
> +function Logins(): React.ReactElement {
Logins 라는 이름을 보니 Login버튼이 여러개 있어야 할것같은데, 일단 로그인 버튼이 하나구요.
만약 로그인 버튼 여러개를 가정하고 구현하신거라면 자식으로 가지고있는 구글 로그인 버튼의 이름이 Login이 아니라 GoogleLoginButton 정도가 되어야 하지 않을까 싶네요

2022-07-10 17:04 UTC, siner308 commented on src/components/Features/Sidebar/SIdebarDetail/Logins/Login.tsx
> +      <header className="App-header">
className이 App이고 header 태그가 붙어있는 것을 보아하니 테스트하실때 App.tsx에 컴포넌트를 직접 넣어서 진행하신걸까요?

2022-07-11 07:19 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Logins/index.tsx
> +function Logins(): React.ReactElement {
이름을 짓다보니, 중복되서 로그인 방법을 여러개 쓰겠다고 저 혼자 생각한 것 같습니다. GoogleLoginButton이 좋아 보여서 이렇게 수정하겠습니다

2022-07-11 11:17 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Logins/index.tsx
> +export default Logins;
제가 sidebar index.tsx를 add 안하다보니 생긴 문제였습니다. 아래 코멘트 반영해서 commit할 때 챙겨서 넣었습니당

2022-07-11 11:17 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Logins/index.tsx
> +function Logins(): React.ReactElement {
반영했습니다.

2022-07-12 15:25 UTC, siner308 commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +import GoogleLogin, { GoogleLoginResponse } from 'react-google-login';
react-google-login 패키지를 사용하셨는데 package.json에 추가는 안되어있네요?

이렇게 되면 제가 코드를 받아서는 실행할 수가 없어요 ㅠㅠ

2022-07-13 06:47 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +/**
넵! 
아하! 없는 거 같습니다. 띄어쓰기랑 불필요한 빈칸을 찾아주는 툴을 오래 찾았었는데 내일 eslint 검색후 적용할께요

2022-07-17 12:45 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +  const onLoginResult = (response: any) => {
onSuccess와 onFailure 를 같은 이벤트로 연결해서 쓰려고 그대로 any로 썼습니다.

2022-07-21 02:17 UTC, gembitious reviewed
아 최종 코멘트를 날려야 되는거군요

2022-07-25 03:26 UTC, Uwa-Tech commented
테스트를 좀 헤매고 있습니다.

2022-08-17 14:45 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +/**
적용했습니다.

2022-08-17 14:45 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +  const onLoginResult = (response: any) => {
api 를 다른 것으로 바꾸면서 any를 사용하지 않고 구현했습니다.

2022-08-17 14:46 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +    console.log(response);
api를 바꾸면서 성공했을 때 Login 이라는 글자만 보이게 했습니다. 완전히 제거하는게 좋을까요?

2022-08-17 14:47 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +          onFailure={onLoginResult}
네 나눠서 구현하다가 오류없이 실행되었지만 로그인은 안되는 현상이 나타나서 다른 api를 사용하였습니다.

2022-08-17 14:48 UTC, Uwa-Tech commented
동영상으로 테스트를 표현했습니다. 이렇게 하면 될까요?

2022-08-25 09:43 UTC, siner308 commented on .vscode/launch.json
> +}
vscode를 쓰지않는 개발자에게 해당 파일은 무의미합니다.
git에 올리지 말아주세요~
.gitignore에 추가해주시면 될것같아요

2022-08-25 09:43 UTC, siner308 commented on package.json
> +    "pip": "0.0.1",
잘못 설치된 패키지일까요?

2022-08-25 09:43 UTC, siner308 commented on public/index.html
> +    <script src="https://apis.google.com/js/platform.js" async defer></script>
index.html에 추가하신 이유가 있을까요?
여기는 전역적으로 반영되는 코드가 있는 곳이라서 구글로그인 한정적인 내용은 로그인 버튼 컴포넌트쪽에 들어가는게 좋아보여요

2022-08-25 09:43 UTC, siner308 commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +import { env } from '../../../../../env'; //env 소스는 '우와'에게 문의 바람.
env 관리가 특정인의 몫이 되면 회사 입장에서는 퇴사했을때 굉장히 애매해지기 때문에 별도의 공용 공간에 두는것을 제안드려요
주석은 제거해주시고 README에 env 관리방법에 대한 내용이 적혀있는게 더 좋을것같습니다

2022-08-25 09:44 UTC, siner308 commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +/**
적용하셨다고 되어있는데 file changes를 보니 적용된 곳을 찾을수가 없네요

2022-08-25 09:45 UTC, siner308 commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +    console.log(response);
로그인 API가 아직 연동되어있지 않으니 이후 수정하시죠~

2022-08-31 02:04 UTC, gembitious requested changes

2022-08-31 02:04 UTC, gembitious commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> + * credentialResponse : 로그인 ID 토큰을 받아옴. (clientId /credential /select_by: "btn")
credentialResponse가 어떤 데이터를 담고 있는지 조금 더 구체적으로 쓰여있어도 좋을 거 같습니다. (괄호 안 내용이 이해 안돼요)

2022-09-07 13:36 UTC, Uwa-Tech commented on package.json
> +    "pip": "0.0.1",
pip 는 잘 못 작성된 부분인 것 같습니다.

2022-09-07 13:42 UTC, Uwa-Tech commented on public/index.html
> +    <script src="https://apis.google.com/js/platform.js" async defer></script>
이것 저것 수정하고 작성하면서 자동으로 입력 된 부분 같습니다. 삭제하고 소스 정리하겠습니다.

2022-09-07 13:47 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> +import { env } from '../../../../../env'; //env 소스는 '우와'에게 문의 바람.
env 관리 방법에 대해 좀더 알아보겠습니다.

2022-09-07 13:51 UTC, Uwa-Tech commented on package.json
> +    "pip": "0.0.1",
axios도.... 이것 저것 손대다가 추가된 부분 인 것 같습니다. 둘다 삭제해도 되는지 확인 후에 삭제 하겠습니다.

2022-09-09 07:27 UTC, siner308 commented on package.json
> +    "pip": "0.0.1",
axios는 제가 과거에 추가한것이고 초록색으로 색칠된부분만 새로 추가된거라 pip만 제거하면 될것같아요~

2022-09-09 07:27 UTC, siner308 commented on .vscode/launch.json
> +}
네 삭제하고 커밋하시면 됩니다~

2022-09-09 07:28 UTC, siner308 commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> + * credentialResponse : 로그인 ID 토큰을 받아옴. (clientId /credential /select_by: "btn")
타입이 있으니까 주석으로 데이터를 알려줄 필요는 없을것같아요

2022-09-09 07:29 UTC, siner308 commented
> 동영상으로 테스트를 표현했습니다. 이렇게 하면 될까요?

네 좋습니다~

2022-09-13 15:12 UTC, Uwa-Tech commented on src/components/Features/Sidebar/SIdebarDetail/Login/GoogleLoginButton.tsx
> + * credentialResponse : 로그인 ID 토큰을 받아옴. (clientId /credential /select_by: "btn")
괄호안의 내용을 삭제 할께요

2022-09-18 05:40 UTC, siner308 commented on .vscode/launch.json
> +}
해당 파일이 삭제되지 않고 ignore에만 추가된것같아요 https://blog.siner.io/2021/08/02/git-cheat-sheet
요기 ignore already committed files 부분 보고 적용해주세요

2022-09-18 05:40 UTC, siner308 commented on src/env.ts
> +  },
이런식으로 이름 명확하게 지어주면 좋을것같습니다

```suggestion
  google: {
    clientId: process.env.REACT_APP_GOOGLE_CLIENT_ID?.toString() || 'error',
  },
```

2022-09-21 04:55 UTC, gembitious approved these changes

2023-10-05 07:27 UTC, merged